//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReportAsois.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
        public int StatusId { get; set; }
        public int SeverityId { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string MapLat { get; set; }
        public string MapLng { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int ViewsNo { get; set; }
        public int VotesNo { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual IssueCategory IssueCategory { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Status Status { get; set; }
        public virtual IssueSubcategory IssueSubcategory { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
